const API_BASE="https://stomko-index4-legal-review.djsynthetics4.chatgpt.site";
const api=(path,options={})=>fetch(API_BASE+path,{credentials:"include",...options});
const users={admin:{name:"Администратор",role:"Полный доступ",avatar:"А",isAdmin:true},manager:{name:"Контент-менеджер",role:"Публикация контента",avatar:"К",isAdmin:false}};
const sections=[
  {id:"overview",icon:"▦",label:"Обзор",group:"Сайт"},{id:"homepage",icon:"⌂",label:"Главная страница"},{id:"slider",icon:"▣",label:"Слайдер"},{id:"doctors",icon:"♟",label:"Врачи",group:"Контент"},{id:"services",icon:"✦",label:"Услуги"},{id:"articles",icon:"≡",label:"Статьи"},{id:"promotions",icon:"%",label:"Акции"},{id:"prices",icon:"₽",label:"Цены"},{id:"contacts",icon:"⌖",label:"Контакты",group:"Настройки"},{id:"seo",icon:"◎",label:"SEO"},{id:"users",icon:"♙",label:"Пользователи",adminOnly:true},{id:"history",icon:"↶",label:"История изменений"}
];
const doctors=[['МЮ','Марков Юрий Сергеевич','Главный врач · стоматолог-ортопед','Оба филиала','published'],['ДВ','Дарьина Валерия Николаевна','Стоматолог-терапевт','Сокол','published'],['ДМ','Девицкий Михаил Александрович','Стоматолог-ортопед, хирург','Беломорская','published'],['КЮ','Кибенко Юлия Дмитриевна','Стоматолог-терапевт','Сокол','published'],['ЕА','Егоров Антон Михайлович','Стоматолог-имплантолог','Оба филиала','published'],['МР','Марков Роман Юрьевич','Стоматолог-ортопед','Беломорская','published'],['РП','Рязанцева Полина Алексеевна','Стоматолог-терапевт','Оба филиала','published'],['ГМ','Голоднова Мария Александровна','Стоматолог-терапевт','Сокол','published']];
const contentData={services:[['Имплантация','Полное восстановление зубов','6 связанных врачей'],['Протезирование','Коронки, виниры и протезы','4 связанных врача'],['Лечение зубов','Терапия и эндодонтия','3 связанных врача'],['Хирургия','Удаление и зубосохраняющие операции','2 связанных врача'],['Диагностика','Современная цифровая диагностика','3 материала'],['Гигиена и отбеливание','Профессиональный уход','4 материала']],articles:[['Санация полости рта','Профилактика','6 минут'],['Как избавиться от зубного налёта','Профилактика','6 минут'],['Кариес: причины и лечение','Лечение зубов','8 минут'],['Пародонтит: симптомы и профилактика','Здоровье дёсен','8 минут'],['Чувствительность зубов','Советы врача','7 минут'],['Виды зубных протезов','Протезирование','9 минут']],promotions:[['Комплексная гигиена','До 30 сентября','Опубликовано'],['Консультация имплантолога','Постоянная акция','Опубликовано'],['Семейная стоматология','Черновик','Не опубликовано']],slider:[['Приём главного врача','Слайд 1','Активен'],['Имплантация с заботой','Слайд 2','Активен'],['Здоровая улыбка','Слайд 3','Скрыт']]};
let currentUser=null,currentSection="overview",liveContent={};
const $=s=>document.querySelector(s), content=$("#content"), modal=$("#editorModal"), toast=$("#toast");

async function login(){const username=$("#loginInput").value.trim(),password=$("#passwordInput").value;const response=await api("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username,password})});if(!response.ok){showToast("Неверный логин или пароль");return}const data=await response.json();currentUser={...data.user,avatar:data.user.name?.[0]||"А",isAdmin:data.user.role==="admin"};const payload=await api("/api/content");if(payload.ok){const result=await payload.json();result.content.forEach(item=>liveContent[item.key]=item.data)}$("#loginView").hidden=true;$("#adminView").hidden=false;$("#userName").textContent=currentUser.name;$("#userRole").textContent=currentUser.role==="admin"?"Полный доступ":"Публикация контента";$("#userAvatar").textContent=currentUser.avatar;renderNav();navigate("overview")}
async function logout(){await api("/api/auth/logout",{method:"POST"});currentUser=null;$("#adminView").hidden=true;$("#loginView").hidden=false}
function renderNav(){let html="",group="";sections.filter(s=>!s.adminOnly||currentUser.isAdmin).forEach(s=>{if(s.group&&s.group!==group){group=s.group;html+=`<div class="nav-group">${group}</div>`}html+=`<button class="nav-item" data-section="${s.id}" type="button"><span>${s.icon}</span><span>${s.label}</span></button>`});$("#mainNav").innerHTML=html}
function navigate(id){currentSection=id;document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.section===id));const meta=sections.find(s=>s.id===id);$("#pageTitle").textContent=meta?.label||"Раздел";$("#pageSubtitle").textContent=subtitle(id);content.innerHTML=render(id);$("#adminView").classList.remove("menu-open")}
function subtitle(id){return {overview:"Состояние сайта и последние изменения",homepage:"Управление блоками главной страницы",slider:"Изображения и предложения в первом экране",doctors:"Специалисты клиники и персональные страницы",services:"Направления лечения и страницы услуг",articles:"Материалы раздела «Здоровые зубы»",promotions:"Специальные предложения клиники",prices:"Прайс-лист и категории услуг",contacts:"Филиалы, телефоны и режим работы",seo:"Поисковая оптимизация страниц",users:"Доступ сотрудников к админке",history:"Все опубликованные изменения"}[id]||"Управление контентом сайта"}
function statusLabel(status){return status==='published'?'<span class="status"><i class="dot"></i> Опубликовано</span>':status==='draft'?'<span class="status draft">Черновик</span>':'<span class="status hidden">Скрыто</span>'}
function render(id){if(id==='overview')return overview();if(id==='doctors')return doctorsPage();if(['services','articles','promotions','slider'].includes(id))return cardsPage(id);if(id==='homepage')return homepage();if(id==='contacts')return contacts();if(id==='seo')return seo();if(id==='users')return usersPage();if(id==='history')return history();if(id==='prices')return prices();return '<div class="empty">Раздел готовится</div>'}
function overview(){return `<div class="stats">${[['♟','8','Врачей на сайте','+2 за месяц'],['✦','6','Страниц услуг','Все опубликованы'],['≡','75','Статей в блоге','+5 за месяц'],['◉','94%','Заполнено SEO','Нужно проверить 4']].map(x=>`<article class="stat-card"><div class="stat-top"><span class="stat-icon">${x[0]}</span><span class="trend">${x[3]}</span></div><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('')}</div><div class="dashboard-grid"><section class="panel"><div class="section-head"><div><h2>Последние изменения</h2><p>Публикации команды за последние дни</p></div><button class="secondary-btn" data-go="history">Все изменения</button></div><div class="activity-list">${[['♟','Обновлена страница Маркова Юрия','Администратор','Сегодня, 11:42'],['≡','Опубликована статья о гигиене','Контент-менеджер','Сегодня, 09:18'],['%','Изменены условия акции','Контент-менеджер','Вчера, 16:05'],['⌖','Обновлён телефон филиала','Администратор','15 сентября, 12:31']].map(x=>`<div class="activity"><span>${x[0]}</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div><time>${x[3]}</time></div>`).join('')}</div></section><aside class="panel"><div class="section-head"><div><h2>Состояние сайта</h2><p>Основные проверки публикации</p></div></div><div class="health"><div class="health-row"><span><i class="dot"></i>Сайт доступен</span><strong>Работает</strong></div><div class="health-row"><span><i class="dot"></i>Последняя публикация</span><strong>8 минут назад</strong></div><div class="health-row"><span><i class="dot"></i>Формы записи</span><strong>Подключены</strong></div><div class="health-row"><span><i class="dot"></i>Резервная копия</span><strong>Сегодня</strong></div></div></aside></div>`}
function doctorsPage(){return `<div class="page-actions"><div><h2>Врачи клиники</h2><p>Карточки на главной и персональные страницы</p></div><button class="primary-btn" data-edit="Новый врач">+ Добавить врача</button></div><section class="table-panel"><div class="toolbar"><div class="search"><span>⌕</span><input data-table-search placeholder="Поиск по имени или должности"></div><button class="secondary-btn">Порядок отображения</button></div><table class="data-table"><thead><tr><th>Врач</th><th>Филиал</th><th>Статус</th><th></th></tr></thead><tbody>${doctors.map(d=>`<tr data-search-row="${(d[1]+' '+d[2]).toLowerCase()}"><td><div class="entity"><span class="entity-avatar">${d[0]}</span><div><strong>${d[1]}</strong><small>${d[2]}</small></div></div></td><td>${d[3]}</td><td>${statusLabel(d[4])}</td><td><div class="row-actions"><button data-edit="${d[1]}" aria-label="Редактировать">✎</button><button aria-label="Дополнительно">⋯</button></div></td></tr>`).join('')}</tbody></table></section>`}
function cardsPage(id){const labels={services:['Услуги','Страницы направлений лечения','Добавить услугу'],articles:['Статьи','Материалы раздела «Здоровые зубы»','Добавить статью'],promotions:['Акции','Предложения и сроки действия','Добавить акцию'],slider:['Слайдер','Первый экран главной страницы','Добавить слайд']},arr=contentData[id];return `<div class="page-actions"><div><h2>${labels[id][0]}</h2><p>${labels[id][1]}</p></div><button class="primary-btn" data-edit="${labels[id][2]}">+ ${labels[id][2]}</button></div><div class="cards-grid">${arr.map((x,i)=>`<article class="content-card"><div class="card-cover"><span class="status ${x[2]?.includes('Черновик')||x[2]?.includes('Скрыт')?'draft':''}">${x[2]||'Опубликовано'}</span><strong>0${i+1}</strong></div><div class="content-card-body"><span class="eyebrow">${x[1]}</span><h3>${x[0]}</h3><p>${id==='slider'?'Изображение, заголовок, текст и кнопка перехода.':'Содержание, изображения, связанные материалы и SEO-параметры.'}</p><footer><small>Изменено недавно</small><button data-edit="${x[0]}">Редактировать →</button></footer></div></article>`).join('')}</div>`}
function homepage(){return `<div class="page-actions"><div><h2>Блоки главной страницы</h2><p>Перетаскивайте блоки, чтобы менять порядок</p></div><button class="primary-btn" data-save>Сохранить порядок</button></div><section class="table-panel"><table class="data-table"><thead><tr><th>Блок</th><th>Содержание</th><th>Показывать</th><th></th></tr></thead><tbody>${[['☰','Первый экран','Слайдер и кнопка записи'],['☰','Услуги','6 карточек направлений'],['☰','Врачи','8 специалистов'],['☰','Акции','3 предложения'],['☰','Здоровые зубы','3 свежие статьи'],['☰','Контакты','Два филиала и карта']].map(x=>`<tr><td><div class="entity"><span class="entity-avatar">${x[0]}</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div></div></td><td>${x[2]}</td><td><span class="status"><i class="dot"></i> Да</span></td><td><button class="secondary-btn" data-edit="${x[1]}">Настроить</button></td></tr>`).join('')}</tbody></table></section>`}
function contacts(){return `<div class="page-actions"><div><h2>Филиалы и контакты</h2><p>Изменения применятся во всех шапках, формах и футере</p></div><button class="primary-btn" data-save>Сохранить контакты</button></div><div class="settings-grid">${[['Сокол','Ленинградский пр-т, 77, к. 4','+7 (926) 074-97-10','8 (499) 158-84-71'],['Беломорская','ул. Беломорская, 26','+7 (916) 204-02-00','8 (495) 451-82-38']].map(x=>`<section class="settings-card"><h3>${x[0]}</h3><label>Адрес<input value="${x[1]}"></label><label>Основной телефон<input value="${x[2]}"></label><label>Дополнительный телефон<input value="${x[3]}"></label><div class="field-grid"><label>Будни<input value="09:00–21:00"></label><label>Суббота<input value="09:00–18:00"></label></div></section>`).join('')}</div>`}
function seo(){return `<div class="page-actions"><div><h2>SEO страниц</h2><p>Заголовки, описания, адреса и индексация</p></div><button class="secondary-btn">Проверить сайт</button></div><section class="table-panel"><table class="data-table"><thead><tr><th>Страница</th><th>SEO-заголовок</th><th>Заполнение</th><th></th></tr></thead><tbody>${[['Главная','Стоматология «Оптимальный выбор» — Москва','100%'],['Имплантация','Имплантация зубов в Москве','100%'],['Протезирование','Протезирование зубов в Москве','92%'],['Врачи','Врачи стоматологии «Оптимальный выбор»','88%'],['Цены','Цены на стоматологические услуги','76%']].map(x=>`<tr><td><strong>${x[0]}</strong></td><td>${x[1]}</td><td><span class="status ${parseInt(x[2])<90?'draft':''}">${x[2]}</span></td><td><button class="secondary-btn" data-edit="SEO: ${x[0]}">Редактировать</button></td></tr>`).join('')}</tbody></table></section>`}
function usersPage(){if(!currentUser.isAdmin)return '<div class="empty">У вас нет доступа к управлению пользователями.</div>';return `<div class="page-actions"><div><h2>Пользователи</h2><p>Доступ к панели управления сайтом</p></div><button class="primary-btn" data-edit="Новый пользователь">+ Добавить пользователя</button></div><section class="table-panel"><table class="data-table"><thead><tr><th>Пользователь</th><th>Роль</th><th>Последний вход</th><th></th></tr></thead><tbody><tr><td><div class="entity"><span class="entity-avatar">А</span><div><strong>Администратор</strong><small>admin</small></div></div></td><td>Полный доступ</td><td>Сейчас</td><td><button class="secondary-btn" data-edit="Администратор">Настроить</button></td></tr><tr><td><div class="entity"><span class="entity-avatar">К</span><div><strong>Контент-менеджер</strong><small>manager</small></div></div></td><td>Контент и публикация</td><td>Сегодня, 09:18</td><td><button class="secondary-btn" data-edit="Контент-менеджер">Настроить</button></td></tr></tbody></table></section>`}
function history(){return `<section class="panel"><div class="section-head"><div><h2>История публикаций</h2><p>Любое изменение можно восстановить</p></div></div><div class="activity-list">${[['♟','Марков Юрий: обновлено описание','Администратор','Сегодня, 11:42'],['≡','Статья «Профессиональная гигиена» опубликована','Контент-менеджер','Сегодня, 09:18'],['%','Акция «Комплексная гигиена» обновлена','Контент-менеджер','Вчера, 16:05'],['▣','Слайдер: заменена фотография','Администратор','16 сентября, 13:40'],['⌖','Обновлён телефон филиала «Сокол»','Администратор','15 сентября, 12:31']].map(x=>`<div class="activity"><span>${x[0]}</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div><time>${x[3]} · <button class="secondary-btn" data-restore>Восстановить</button></time></div>`).join('')}</div></section>`}
function prices(){return `<div class="page-actions"><div><h2>Прайс-лист</h2><p>Категории и стоимость услуг</p></div><button class="primary-btn" data-edit="Новая позиция прайса">+ Добавить позицию</button></div><section class="table-panel"><div class="toolbar"><div class="search"><span>⌕</span><input placeholder="Поиск по прайсу"></div><button class="secondary-btn">Импортировать Excel</button></div><table class="data-table"><thead><tr><th>Услуга</th><th>Категория</th><th>Цена</th><th></th></tr></thead><tbody>${[['Первичная консультация','Терапия','от 1 500 ₽'],['Лечение кариеса','Терапия','от 6 500 ₽'],['Профессиональная гигиена','Профилактика','от 7 000 ₽'],['Имплантация зуба','Имплантация','от 45 000 ₽']].map(x=>`<tr><td><strong>${x[0]}</strong></td><td>${x[1]}</td><td>${x[2]}</td><td><button class="secondary-btn" data-edit="${x[0]}">Изменить</button></td></tr>`).join('')}</tbody></table></section>`}
function openEditor(title){$("#modalTitle").textContent=title;modal.hidden=false;document.body.style.overflow="hidden"}
function closeEditor(){modal.hidden=true;document.body.style.overflow=""}
function showToast(message){toast.textContent='✓ '+message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}

$("#loginForm").addEventListener("submit",e=>{e.preventDefault();login()});
document.querySelectorAll("[data-demo-user]").forEach(b=>b.addEventListener("click",()=>{const u=b.dataset.demoUser;$("#loginInput").value=u;$("#passwordInput").value=u==="admin"?"stomko2026":"content2026"}));
$("#togglePassword").addEventListener("click",()=>{const i=$("#passwordInput");i.type=i.type==='password'?'text':'password'});$("#logoutBtn").addEventListener("click",logout);$("#menuToggle").addEventListener("click",()=>$("#adminView").classList.toggle("menu-open"));
$("#mainNav").addEventListener("click",e=>{const b=e.target.closest("[data-section]");if(b)navigate(b.dataset.section)});
content.addEventListener("click",async e=>{const edit=e.target.closest("[data-edit]"),go=e.target.closest("[data-go]");if(edit)openEditor(edit.dataset.edit);if(go)navigate(go.dataset.go);if(e.target.closest("[data-save]")){if(currentSection==="contacts"){const cards=[...content.querySelectorAll('.settings-card')];const values=cards.map(card=>{const fields=[...card.querySelectorAll('input')].map(x=>x.value);return fields});const contacts={sokol:{address:values[0]?.[0]||'',primary:values[0]?.[1]||'',additional:[values[0]?.[2]||'']},belomorskaya:{address:values[1]?.[0]||'',primary:values[1]?.[1]||'',additional:[values[1]?.[2]||'']}};await api('/api/content/contacts',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({data:contacts})});showToast('Контакты сохранены и опубликованы')}else showToast("Изменения сохранены и опубликованы")};if(e.target.closest("[data-restore]"))showToast("Предыдущая версия восстановлена")});
content.addEventListener("input",e=>{if(e.target.matches("[data-table-search]")){const q=e.target.value.toLowerCase();document.querySelectorAll("[data-search-row]").forEach(r=>r.hidden=!r.dataset.searchRow.includes(q))}});
document.querySelectorAll("[data-close-modal]").forEach(b=>b.addEventListener("click",closeEditor));document.querySelectorAll("[data-editor-tab]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-editor-tab]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll("[data-editor-pane]").forEach(x=>x.classList.toggle("active",x.dataset.editorPane===b.dataset.editorTab))}));
$("#editorForm").addEventListener("submit",async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());await api("/api/content/editor",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({data:{title:data.title||"",role:data.role||"",description:data.description||""}})});closeEditor();showToast("Изменения сохранены в базе сайта")});$("#openSite").addEventListener("click",()=>window.open("https://hamsterwar.github.io/Stomko_v2/","_blank","noopener"));
document.addEventListener("keydown",e=>{if(e.key==='Escape'&&!modal.hidden)closeEditor()});

function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;ctx.registerTool({name:"navigate_admin_section",title:"Открыть раздел админки",description:"Открывает указанный раздел прототипа панели управления",inputSchema:{type:"object",properties:{section:{type:"string",enum:sections.map(s=>s.id)}},required:["section"],additionalProperties:false},annotations:{readOnlyHint:true},execute({section}){if(!currentUser)throw new Error("Сначала выполните вход");navigate(section);return{section}}});ctx.registerTool({name:"open_content_editor",title:"Редактировать материал",description:"Открывает форму редактирования выбранного материала",inputSchema:{type:"object",properties:{title:{type:"string",minLength:1}},required:["title"],additionalProperties:false},annotations:{readOnlyHint:false},execute({title}){if(!currentUser)throw new Error("Сначала выполните вход");openEditor(title);return{opened:true,title}}})}
registerWebMCP();api("/api/auth/me").then(async response=>{if(!response.ok)return;const data=await response.json();currentUser={...data.user,avatar:data.user.name?.[0]||"А",isAdmin:data.user.role==="admin"};$("#loginView").hidden=true;$("#adminView").hidden=false;$("#userName").textContent=currentUser.name;$("#userRole").textContent=currentUser.role==="admin"?"Полный доступ":"Публикация контента";$("#userAvatar").textContent=currentUser.avatar;renderNav();navigate("overview")});
